# Definition of Tensor:
* A PyTorch Tensor is basically the same as a numpy array
* It does not know anything about deep learning or computational graphs or gradients, and is just a generic n-dimensional array to be used for arbitrary numeric computation.
* Pytorch uses Tensor to encode inputs, outputs and model's parameters.

### Tensors vs np Arrays:
* similar except that tensors can run on GPUs. Both can share same underlying memory.
* Another diff is that Tensors are optimised for automatic differentiation.


## Types of Tensor : Float and Int ( 2 Types in pytorch)
### Precision


1.   64-bit
* Float: float64, double -> DoubleTensor
* Int: int64, long -> LongTensor

2.   32-bit
* Float: float32, float -> FloatTensor
* Int: int32, int -> IntTensor

3.   16-bit
* Float: float16, half -> HalfTensor
* Int, int16, short -> ShortTensor

4.   8-bit
* Signed: int8 -> ByteTensor
* Unsigned: uint8 -> CharTensor


# Tensor Initialisation
### Initialising tensor would require 3 declarations:
1. dtype

2. device

3. requires_grad

In [1]:
import torch
import numpy as np

In [2]:
# [1] dtype
# torch.float32, torch.float16 etc

# [2] device
device = "cuda" if torch.cuda.is_available() else "cpu"

# [3] requires_grad = True/False

my_tensor = torch.tensor([[1,2,3],[4,5,6]], \
                         dtype = torch.float32, \
                         device = 'cuda' ,\
                         requires_grad = True)
print(my_tensor)

RuntimeError: ignored

In [ ]:
# Attibutes of Tensor
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

# tensor from CPU to GPU
# tensor.to('cuda')

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


In [ ]:
# NOTE: A Tensor can be created by using torch.Tensor or torch.FloatTensor(captital T) and torch.tensor([])
# Default type for torch.Tensor -> float32 i.e. Float Tensor and Default type for torch.tensor -> int64 i.e. Long Tensor
# Also cannot define dtype for torch.Tensor which is made to be used as float32. Can change dtype for torch.tensor

tensor = torch.Tensor([1,2,3]) # only float 32
print(tensor)
print(tensor.dtype)

tensor = torch.tensor([1,2,3]) # any dtype
print(tensor)
print(tensor.dtype)

tensor([1., 2., 3.])
torch.float32
tensor([1, 2, 3])
torch.int64


In [ ]:
# tensor = torch.Tensor([1,2,3],dtype = torch.float64)  # error as dtype can only be torch.float32 for torch.Tensor() and any other type for torch.tensor()

TypeError: ignored

### Other Common Initialisations

1. empty
2. zeros
3. rand
4. ones
5. eye ; Identity Matrix
6. arange ; ~ to range in python


In [ ]:
x = torch.empty(size=(3,3))
print(x)

tensor([[1.8531e-18, 4.5722e-41, 1.8531e-18],
        [4.5722e-41, 4.4842e-44, 0.0000e+00],
        [8.9683e-44, 0.0000e+00, 2.4016e-34]])


In [ ]:
x = torch.zeros(size=(3,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
x = torch.rand(size=(3,3))
print(x)

tensor([[0.3825, 0.6685, 0.9143],
        [0.1755, 0.5724, 0.7883],
        [0.4378, 0.6555, 0.2718]])


In [ ]:
x = torch.ones(size=(3,3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
x = torch.eye(3,3)
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
x = torch.arange(start = 3,end = 10, step=1)
print(x)

tensor([3, 4, 5, 6, 7, 8, 9])


In [ ]:
x = torch.linspace(start = 0.1,end = 1, steps=10)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


## Distribution

In [3]:
x = torch.empty(size = (1,5)).normal_(mean=0,std=1)
print(x)

tensor([[ 0.2485,  0.4313,  0.5599, -0.4909,  2.0655]])


In [4]:
x = torch.empty(size = (1,5)).uniform_(0,1) # becomes similar to rand
print(x)

tensor([[0.4793, 0.2288, 0.1678, 0.9231, 0.3348]])


# Convert Tensors

In [ ]:
import torch
# Convert tensor to other types:
tensor = torch.arange(4)
print(tensor)
print(tensor.bool()) # True/False
print(tensor.type())

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
torch.LongTensor


In [ ]:
tensor = torch.tensor([1,2,3])  # will result similarly for torch.Tensor([])

new_tensor = tensor.type(torch.HalfTensor)
print(new_tensor.type())

# all floats
new_tensor = tensor.double()
print(new_tensor.type())

new_tensor = tensor.float()
print(new_tensor.type())

new_tensor = tensor.half()
print(new_tensor.type())

new_tensor = tensor.byte()
print(new_tensor.type())

# all ints
new_tensor = tensor.long()
print(new_tensor.type())

new_tensor = tensor.int()
print(new_tensor.type())

new_tensor = tensor.short()
print(new_tensor.type())

new_tensor = tensor.char()
print(new_tensor.type())

torch.HalfTensor
torch.DoubleTensor
torch.FloatTensor
torch.HalfTensor
torch.ByteTensor
torch.LongTensor
torch.IntTensor
torch.ShortTensor
torch.CharTensor


In [ ]:
tensor = torch.Tensor([1,2,3])


torch.HalfTensor
torch.DoubleTensor


# Array To Tensor Conversion

In [ ]:
import numpy as np
np_array = np.zeros((5,5))

tensor = torch.from_numpy(np_array)
print('Numpy to Tensor',type(tensor))

np_array_back = tensor.numpy()
print('Tensor to Numpy',type(np_array_back))



Numpy to Tensor <class 'torch.Tensor'>
Tensor to Numpy <class 'numpy.ndarray'>


## Tensor Math & Comparison Operations

In [ ]:
import torch

x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

In [ ]:
# Addition - 3 ways
# (i) torch.ops(tensor1,tensor2,output = z)
# (ii) z = torch.ops(tensor1,tensor2)
# (iii) z = tensor1 + tensor2
# (iv) z = tensor1.ops_(tensor2)
# (v) z =



# (i) using empty tensor
z1 = torch.empty(3)
torch.add(x,y,out=z1)
print('z1',z1)

# (ii) using .add
z2 = torch.add(x,y)
print('z2',z2)

# (iii) using + operation
z3 = x+y
print('z3',z3)

z1 tensor([10., 10., 10.])
z2 tensor([10, 10, 10])
z3 tensor([10, 10, 10])


In [ ]:
# Subtraction
z1=x-y
print('z1',z1)

z1 tensor([-8, -6, -4])


In [ ]:
# Division - true_divide does the element-wise division of matrices
z = torch.true_divide(x,y)
print('z',z)

z tensor([0.2500, 0.4000, 0.5000])


In [ ]:
# Exponentiation - pow does elementwise exponentiation
z = x.pow(2)
print('z',z)
z = x**2
print('z',z)

z tensor([1, 4, 9])
z tensor([1, 4, 9])


In [ ]:
# inplace operations
t = torch.zeros(3)

# (i) tensor1.ops_(tensor2) Add underscore "_" after the operation name
t.add_(x)
print(t)

# (ii)
t+=x
print(t)

tensor([1., 2., 3.])
tensor([2., 4., 6.])


In [ ]:
# simple comparison
z = x>0
print('z',z)

z = x<0
print('z',z)

z tensor([True, True, True])
z tensor([False, False, False])


## Matrix Operations

In [ ]:
# Matrix Multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

# (i) .mm
x3 = torch.mm(x1,x2)
print('x3',x3)

# (ii)
x3 = x1.mm(x2)
print('x3',x3)


x3 tensor([[1.4781, 1.0279, 1.4752],
        [0.8695, 0.5285, 1.1405]])
x3 tensor([[1.4781, 1.0279, 1.4752],
        [0.8695, 0.5285, 1.1405]])


In [ ]:
# element wise multiplication
x = torch.ones(3,3)*3
y = torch.ones(3,3)*2
print(x,y)

z = x*y
print('z',z)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]) tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
z tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])


## Broadcasting
While operating on two different matrices, the matrix with lower dimension is broadcasted to the one with higher dimension.
* eg. (1,5) x2 is broadcasted to (5,5) in x1.

In [ ]:
# ROW Broadcasting
x1 = torch.ones((5,5))*3
x2 = torch.ones((1,5))*2

print(x1)
print(x2)

z = x1-x2
print(z)
z = x1**x2
print(z)

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
tensor([[2., 2., 2., 2., 2.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.]])


In [ ]:
# COLUMN Broadcasting
x1 = torch.ones((5,5))*3
x2 = torch.ones((5,1))*2

print(x1)
print(x2)

z = x1-x2
print(z)
z = x1**x2
print(z)

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
tensor([[2.],
        [2.],
        [2.],
        [2.],
        [2.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.]])


## Other useful tensor operations

In [ ]:
x = torch.tensor([-1,2,3,4])

# sum of all elements
sum_x = torch.sum(x,dim=0)
print('sum_x',sum_x)

sum_x tensor(8)


In [ ]:
# max-min values and their indices

values,indices = torch.max(x,dim=0)
print('values,indices',values,indices)

values,indices = torch.min(x,dim=0)
print('values,indices',values,indices)


values,indices tensor(4) tensor(3)
values,indices tensor(-1) tensor(0)


In [ ]:
# absolute values
abs_x = torch.abs(x)
print('abs_x',abs_x)

abs_x tensor([1, 2, 3, 4])


In [ ]:
# index with maximum value
z = torch.argmax(x,dim=0)
print('z',z)

# index with minimum value
z = torch.argmin(x,dim=0)
print('z',z)

z tensor(3)
z tensor(0)


In [ ]:
# mean of elements
mean_x = torch.mean(x.float(),dim=0)
mean_x

tensor(2.)

In [9]:
# check if two tensors are equal element-wise

x= torch.tensor([1,2,3])
y= torch.tensor([1,2,4])

z = torch.eq(x,y)
print(z)



tensor([ True,  True, False])


In [10]:

# sorting array

torch.sort(y,dim=0,descending=False)


torch.return_types.sort(
values=tensor([1, 2, 4]),
indices=tensor([0, 1, 2]))

In [5]:
# clamping tensor based on min and max values. All values less than min value would become the min value and
# all values greater than max value would become the max value.
x = torch.tensor([[-1,-2,3,4],[5,6,11,13]])
print('x',x)

z = torch.clamp(x,min=0,max=10)
print('z',z)

# Note that torch.clamp(x,min=0) becomes a relu function


x tensor([[-1, -2,  3,  4],
        [ 5,  6, 11, 13]])
z tensor([[ 0,  0,  3,  4],
        [ 5,  6, 10, 10]])


In [ ]:
x = torch.tensor( [1,0,1,1,1] , dtype = torch.bool )
z = torch.any(x)
print('z',z)
z = torch.all(x)
print('z',z)

z tensor(True)
z tensor(False)


## Tensor Indexing

In [11]:
batch_size = 10
features = 25
x = torch.rand((batch_size,features))

print(x.shape)

# first example
print(x[0].shape)

# first feature of all example
print(x[:,0].shape)

print(x[2,0:10])


torch.Size([10, 25])
torch.Size([25])
torch.Size([10])
tensor([0.5135, 0.7785, 0.0127, 0.9086, 0.5344, 0.2985, 0.1792, 0.8737, 0.0517,
        0.8843])


In [14]:
# fancy indexing
# [i]
x = torch.arange(10,20)
print(x)
indices = [2,5,8]
print(x[indices])

# [ii]
x = torch.rand((3,5))
print(x)
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(rows,cols)
print(x[rows,cols])
print(x[rows,cols].shape)


tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
tensor([12, 15, 18])
tensor([[0.9964, 0.1489, 0.0907, 0.2917, 0.3452],
        [0.0817, 0.7239, 0.4308, 0.2942, 0.1263],
        [0.9523, 0.0301, 0.5777, 0.1209, 0.0624]])
tensor([1, 0]) tensor([4, 0])
tensor([0.1263, 0.9964])
torch.Size([2])


In [ ]:
# More advanced indexing
x = torch.arange(10)
print(x[ (x<2) | (x>8) ])

x = torch.arange(10)
print(x[ (x>2) & (x<8) ])

print(x[x.remainder(2)==0])

tensor([0, 1, 9])
tensor([3, 4, 5, 6, 7])
tensor([0, 2, 4, 6, 8])


In [ ]:
torch.where(x>5,x,x*2) # if x>5; print(x) else print(x*2)

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

## Tensor Reshaping

In [ ]:
x = torch.arange(9)
print('x',x)

x tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [ ]:
# converting it into 3x3 matrix
x_3x3 = x.view(3,3)
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [ ]:
x_3x3 = x.reshape(3,3)
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [ ]:
# view vs reshape.
'''
view needs the data to be contiguous. for eg. if we have
x = torch.arange(9) i.e. x = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

x_3x3 will show the numbers in matrix form but the data would be contiguous.
Thus y=x_3x3.T will transform the matrix which will change the way data is stored
i.e. [0,3,6,1,4,7,2,5,8] instead of [0,1,2,3,4,5,6,7,8]
Then, y.view(9) will throw error.
Reshape works fine for non-contiguous data.
'''
x = torch.arange(9)
x_3x3 = x.view(3,3)
y = x_3x3.T
y.view(9)  # y.reshape(9) works for reshaping or y.contiguous().view(9)

RuntimeError: ignored

In [ ]:
#######################################################
# contiguous vs non-contiguous Tensors
#######################################################
# is_contiguous() method to check if a tensor is contiguous or not
# stride() returns the #jumps required to reach new row and new column eg. (3,1) represents 3 jumps for new row and 1 jump for new column
# tensor.contiguous() returns itself if contiguoug or copies the data and makes them contiguous

tensor = torch.arange(12).reshape(4,3)
print(tensor)
print(tensor.is_contiguous())
print(tensor.contiguous())
print(tensor.stride())

tensor = tensor.T
print(tensor)
print(tensor.is_contiguous())
print(tensor.stride()) # incorrect
tensor = tensor.contiguous()
print(tensor.is_contiguous())
print(tensor.stride()) # correct


tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
True
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
(3, 1)
tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])
False
(1, 3)
True
(4, 1)


In [ ]:
# concatenation
x1 = torch.rand((32,3,64,64))
x2 = torch.rand((32,3,64,64))
print( torch.cat((x1,x2),dim=0).shape )
print( torch.cat((x1,x2),dim=1).shape )

torch.Size([64, 3, 64, 64])
torch.Size([32, 6, 64, 64])


In [ ]:
# flatten keeping batchsize
batch=64
x = torch.rand((batch,2,5))
z = x.view(batch,-1)
print(z.shape)

torch.Size([64, 10])


In [ ]:
# suppose want to tanspose the matrix keeping the batch size
# i.e. (64,2,5) should become (64,5,2)
# x.permute(0,2,1) i.e. 0th dim will be at 0th dim ; 2nd dim will be at 1st dim and 1st dim will be at 2nd dim
z = x.permute(0,2,1)
print(z.shape)

torch.Size([64, 5, 2])


In [ ]:
###############################
# squeeze vs unsqueeze  -  remove/add dimension
###############################
# works with only 1 as a dimension.

# add dimensionality
x = torch.arange(10) # already dim of 10
print(x,x.shape)
z1 = x.unsqueeze(0) # adding dim as 1,10
print(z1,z1.shape)
z2 = x.unsqueeze(1) # adding dim as 10,1
print(z2,z2.shape)


# remove dimensionality
x = torch.rand(1,1,6)
print(x)
x = x.squeeze(0)
print(x.shape)

new_x = x.squeeze(1)
print(new_x.shape)


x = torch.rand(2,1,6)
x = x.squeeze(0)   # doesnt work with non-one index
print(x.shape)

x = x.squeeze(1)
print(x.shape)



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([10])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 10])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]) torch.Size([10, 1])
tensor([[[0.9863, 0.6243, 0.2603, 0.5062, 0.8142, 0.2462]]])
torch.Size([1, 6])
torch.Size([1, 6])
torch.Size([2, 1, 6])
torch.Size([2, 6])


In [15]:

'''
Numpy to torch and vice versa can only be done on CPU. Here, we will shift tensors to GPU, where all the matrix multiplication
operations are much faster. Then, while converting the tensor, python will throw an error which can be resolved by shifting
the tensor on cpu first.
'''
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5,device = device)   # tensor x on GPU
  y = torch.ones(5)
  y = y.to(device)  # tensor y on GPU
  z = x + y
  print(z)
  try:
    z = np.array(z)
  except:
    print('ERROR: Cant Convert torch to numpy or vice-versa on gpu. First get tensors on cpu ')
  z = z.to("cpu")
  z = np.array(z)
  print(z)

In [ ]:
# complete